helix = "/Users/iobt/personal/helix"
main = "/Users/iobt/brightidea/main"
whiteboard = "/Users/iobt/brightidea/main/whiteboard"
practice = "/Users/iobt/personal/practice"
proc-macro-workshop = "/Users/iobt/personal/proc-macro-workshop"
fractal = "/Users/iobt/brightidea/main/fractal"
sqlite = "/Users/iobt/personal/sqlite"
sqlite-amalgation = "/Users/iobt/personal/sqlite-amalgation"
taffy = "/Users/iobt/personal/taffy"
tlpdb-go = "/Users/iobt/projects/tlpdb-go"
dsa4212 = "/Users/iobt/Library/CloudStorage/OneDrive-NationalUniversityofSingapore/school/y3s2/dsa4212"
